
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nori07
 */
public class AplikasiKasirGUI extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKasirGUI
     */
    public AplikasiKasirGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBnamaMakanan = new javax.swing.JComboBox<>();
        TFjumlahBeli = new javax.swing.JTextField();
        BhitungJumlahHarga = new javax.swing.JButton();
        RBbungkus = new javax.swing.JRadioButton();
        RBmakanDiSini = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bbayar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXThargaMakanan = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTjumlahHarga = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TXTjumlahBayar = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        TXTjumlahKembalian = new javax.swing.JTextPane();
        CBpph10 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA MAKANAN");

        jLabel2.setText("HARGA MAKANAN");

        jLabel3.setText("JUMLAH BELI");

        jLabel4.setText("JUMLAH HARGA");

        jLabel5.setText("JUMLAH BAYAR");

        jLabel6.setText("JUMLAH KEMBALIAN");

        CBnamaMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH MENU", "MI AYAM", "AYAM BAKAR", "NASI GORENG", "SATE AYAM"}));
        CBnamaMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBnamaMakananActionPerformed(evt);
            }
        });

        TFjumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFjumlahBeliActionPerformed(evt);
            }
        });

        BhitungJumlahHarga.setText("HITUNG JUMLAH HARGA");
        BhitungJumlahHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhitungJumlahHargaActionPerformed(evt);
            }
        });

        RBbungkus.setText("BUNGKUS");
        RBbungkus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbungkusActionPerformed(evt);
            }
        });

        RBmakanDiSini.setText("MAKAN DI SINI");
        RBmakanDiSini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBmakanDiSiniActionPerformed(evt);
            }
        });

        jButton2.setText("BATAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("KELUAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Bbayar.setText("BAYAR");
        Bbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbayarActionPerformed(evt);
            }
        });

        TXThargaMakanan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(TXThargaMakanan);

        jScrollPane2.setViewportView(TXTjumlahHarga);

        jScrollPane3.setViewportView(TXTjumlahBayar);

        jScrollPane4.setViewportView(TXTjumlahKembalian);

        CBpph10.setText("PPH 10%");
        CBpph10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBpph10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBnamaMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFjumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BhitungJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RBbungkus, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RBmakanDiSini, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(CBpph10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Bbayar, BhitungJumlahHarga, CBnamaMakanan, TFjumlahBeli, jScrollPane1, jScrollPane2, jScrollPane3, jScrollPane4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBnamaMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFjumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BhitungJumlahHarga)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBbungkus)
                    .addComponent(RBmakanDiSini))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bbayar)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBpph10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BhitungJumlahHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhitungJumlahHargaActionPerformed
        // TODO add your handling code here:
        Double harga, jumlah, hasil;
        harga = Double.valueOf(TXThargaMakanan.getText());
        jumlah = Double.valueOf(TFjumlahBeli.getText());
        hasil = harga*jumlah;
        TXTjumlahHarga.setText(String.valueOf(hasil));
    }//GEN-LAST:event_BhitungJumlahHargaActionPerformed

    private void CBnamaMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBnamaMakananActionPerformed
        // TODO add your handling code here:
        if (CBnamaMakanan.getSelectedItem() == "MI AYAM") {
            TXThargaMakanan.setText("10000");
        }else if(CBnamaMakanan.getSelectedItem() == "AYAM BAKAR") {
            TXThargaMakanan.setText("20000");
        }else if(CBnamaMakanan.getSelectedItem() == "NASI GORENG") {
            TXThargaMakanan.setText("12000");
        }else if(CBnamaMakanan.getSelectedItem() == "SATE AYAM") {
            TXThargaMakanan.setText("15000");
        }
    }//GEN-LAST:event_CBnamaMakananActionPerformed

    private void CBpph10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpph10ActionPerformed
        // TODO add your handling code here:
        Double pph, kembalian;
        pph = Double.valueOf(TXTjumlahHarga.getText())/10;
        kembalian = Double.valueOf(TXTjumlahBayar.getText()) - Double.valueOf(TXTjumlahHarga.getText());
        kembalian = kembalian - pph;
        TXTjumlahKembalian.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_CBpph10ActionPerformed
    
    
    private void RBbungkusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbungkusActionPerformed
        // TODO add your handling code here:
        Double harga, jumlah, hasil;
        harga = Double.valueOf(TXThargaMakanan.getText());
        jumlah = Double.valueOf(TFjumlahBeli.getText());
        hasil = (harga*jumlah)+2000;
        TXTjumlahHarga.setText(String.valueOf(hasil));
    }//GEN-LAST:event_RBbungkusActionPerformed

    private void RBmakanDiSiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBmakanDiSiniActionPerformed
        // TODO add your handling code here:
        Double harga, jumlah, hasil;
        harga = Double.valueOf(TXThargaMakanan.getText());
        jumlah = Double.valueOf(TFjumlahBeli.getText());
        hasil = harga*jumlah;
        TXTjumlahHarga.setText(String.valueOf(hasil));
    }//GEN-LAST:event_RBmakanDiSiniActionPerformed

    private void BbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbayarActionPerformed
         // TODO add your handling code here:
        Double totalHarga, totalBayar, kembalian;
        totalHarga = Double.valueOf(TXTjumlahHarga.getText());
        totalBayar = Double.valueOf(TXTjumlahBayar.getText());
        kembalian = totalBayar - totalHarga;
        TXTjumlahKembalian.setText(String.valueOf(kembalian));
        
    }//GEN-LAST:event_BbayarActionPerformed

    private void TFjumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFjumlahBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFjumlahBeliActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int keluar = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin melanjutkan?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (keluar == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            System.out.println("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int batal = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin melanjutkan?", "Batal", JOptionPane.YES_NO_OPTION);
        if (batal == JOptionPane.YES_OPTION) {
            CBnamaMakanan.setSelectedIndex(0);
            TXThargaMakanan.setText("");
            TFjumlahBeli.setText("");
            TXTjumlahHarga.setText("");
            RBbungkus.setSelected(false);
            RBmakanDiSini.setSelected(false);
            TXTjumlahBayar.setText("");
            TXTjumlahKembalian.setText("");
            CBpph10.setSelected(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKasirGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bbayar;
    private javax.swing.JButton BhitungJumlahHarga;
    private javax.swing.JComboBox<String> CBnamaMakanan;
    private javax.swing.JCheckBox CBpph10;
    private javax.swing.JRadioButton RBbungkus;
    private javax.swing.JRadioButton RBmakanDiSini;
    private javax.swing.JTextField TFjumlahBeli;
    private javax.swing.JTextPane TXThargaMakanan;
    private javax.swing.JTextPane TXTjumlahBayar;
    private javax.swing.JTextPane TXTjumlahHarga;
    private javax.swing.JTextPane TXTjumlahKembalian;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
